from typing import Final

FREE_SPACE: Final = "FREE SPACE"

QUESTIONS: Final[list[str]] = [
    "uses vim keybindings",
    "dark mode all day",
    "writes tests before code",
    "ships on friday anyway",
    "has 20+ browser tabs open",
    "uses ai coding assistant daily",
    "renames variables three times",
    "debugs with print statements",
    "has a custom ide theme",
    "swears by keyboard shortcuts",
    "pair programs every week",
    "still has a TODO from last year",
    "uses docker for local dev",
    "rebases instead of merge commits",
    "has a standing desk setup",
    "says it works on my machine",
    "reviews prs on mobile",
    "keeps terminal split panes",
    "talks to rubber duck to debug",
    "celebrates zero lint warnings",
    "uses tabs over spaces",
    "names branches with ticket ids",
    "has automated dotfiles setup",
    "listens to lo-fi while coding",
    "has broken prod at least once",
    "opens docs before asking slack",
    "uses more than one ide",
    "has a favorite cli tool",
    "attends tech meetups or conferences",
]
